// ============================================================================
// core/obsidian-bus/tests/cross_language.rs
//
// Authorized by: user instruction — "cross-language test for this crate ...
// ships in core/obsidian-bus/tests/".
//
// This test loads `test-vectors/envelopes.json` and asserts that the current
// Rust canonicalizer produces byte-identical output for every named vector.
// The SAME JSON file is the source of truth for the Python mirror in
// `obsidian_agent.bus` (next commit). Both languages reading the same file
// and producing the same bytes IS the cross-language harness.
//
// The JSON file is generated by `cargo run --example emit-vectors`. It is
// committed to the repo so that:
//   - CI in a language that can't easily run cargo still has the vectors,
//   - a vector change is an explicit commit (diff against old values),
//   - accidental canonicalizer changes are caught by this test failing.
//
// If the JSON file is missing (fresh clone before `emit-vectors` has run),
// this test is skipped with a clear message. The acceptance gate for M0
// requires the file to be present and all vectors to pass.
// ============================================================================

use obsidian_bus::canonical::canonicalize_envelope;
use obsidian_bus::proto::Envelope;
use prost::Message as ProstMessage;
use std::fs;
use std::path::PathBuf;

const VECTORS_PATH: &str = "test-vectors/envelopes.json";

#[derive(serde::Deserialize)]
struct VectorsFile {
    version: String,
    schema_version: String,
    vectors: Vec<VectorEntry>,
}

#[derive(serde::Deserialize)]
struct VectorEntry {
    name: String,
    /// The full binary envelope (including signature) encoded with prost,
    /// then hex-encoded. We use this rather than per-field JSON to sidestep
    /// the JSON/proto mapping question — what we actually care about here
    /// is byte-for-byte canonical output given a known envelope.
    envelope_proto_hex: String,
    /// Expected canonicalize_envelope output, hex-encoded.
    canonical_hex: String,
}

fn load_vectors() -> Option<VectorsFile> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let path = manifest_dir.join(VECTORS_PATH);
    if !path.exists() {
        return None;
    }
    let raw = fs::read_to_string(&path).expect("failed to read vectors file");
    Some(serde_json::from_str(&raw).expect("vectors JSON is malformed"))
}

fn hex_decode(s: &str) -> Vec<u8> {
    let s = s.trim();
    let mut out = Vec::with_capacity(s.len() / 2);
    let bytes = s.as_bytes();
    let mut i = 0;
    while i + 1 < bytes.len() {
        let hi = from_hex(bytes[i]);
        let lo = from_hex(bytes[i + 1]);
        out.push((hi << 4) | lo);
        i += 2;
    }
    out
}

fn from_hex(c: u8) -> u8 {
    match c {
        b'0'..=b'9' => c - b'0',
        b'a'..=b'f' => c - b'a' + 10,
        b'A'..=b'F' => c - b'A' + 10,
        _ => panic!("bad hex char: {}", c as char),
    }
}

fn hex_encode(b: &[u8]) -> String {
    let mut s = String::with_capacity(b.len() * 2);
    for x in b {
        s.push_str(&format!("{:02x}", x));
    }
    s
}

#[test]
fn cross_language_vectors_match_current_canonicalizer() {
    let vectors = match load_vectors() {
        Some(v) => v,
        None => {
            eprintln!(
                "SKIP: {} not found. Run `cargo run --example emit-vectors` to generate.",
                VECTORS_PATH
            );
            return;
        }
    };

    assert_eq!(
        vectors.version, "1",
        "unknown vectors file version: {}",
        vectors.version
    );
    assert_eq!(
        vectors.schema_version, "1.0.0",
        "envelope schema version in vectors file does not match current"
    );
    assert!(!vectors.vectors.is_empty(), "vectors file is empty");

    for v in vectors.vectors {
        let envelope_bytes = hex_decode(&v.envelope_proto_hex);
        let envelope = Envelope::decode(&*envelope_bytes)
            .unwrap_or_else(|e| panic!("vector '{}' envelope_proto_hex is malformed: {e}", v.name));

        let got = hex_encode(&canonicalize_envelope(&envelope));
        let want = v.canonical_hex.trim().to_string();

        assert_eq!(
            got, want,
            "vector '{}' canonicalization mismatch.\n  got : {got}\n  want: {want}",
            v.name
        );
    }
}
