"""Canonical envelope serialization for signing and verification.

AUTHORIZED BY: M0 plan §"Build order" step 4; ADR 0003; user instruction on
cross-language test harness.

This module is a byte-for-byte mirror of ``core/obsidian-bus/src/canonical.rs``.
Any change here MUST be matched in the Rust source; the cross-language test
at ``tests/test_bus_cross_language.py`` is the firewall.

See the Rust source for the full rules. Summary:

  1. Fields emitted in ascending tag order.
  2. Scalar fields at proto3 zero-value are OMITTED, EXCEPT:
     - ``payload`` (tag 9, bytes) is ALWAYS emitted length-prefixed.
     - ``nonce`` (tag 12, bytes) is ALWAYS emitted length-prefixed.
  3. ``signature`` (tag 13) is NEVER emitted.
  4. Repeated strings preserve order, one tag per element.
  5. Integer varints use plain proto3 encoding (not zigzag).
  6. Timestamps canonicalize recursively under proto3 defaults-stripped rules.
"""

from __future__ import annotations

# Wire types from the protobuf spec.
_WIRE_VARINT = 0
_WIRE_LENGTH_DELIMITED = 2


def _write_varint(out: bytearray, value: int) -> None:
    """Encode an unsigned varint (7 bits per byte, MSB continuation)."""
    while value >= 0x80:
        out.append((value & 0x7F) | 0x80)
        value >>= 7
    out.append(value & 0xFF)


def _write_tag(out: bytearray, field_number: int, wire_type: int) -> None:
    tag = (field_number << 3) | (wire_type & 0b111)
    _write_varint(out, tag)


def _write_varint_tag(out: bytearray, field_number: int, value: int) -> None:
    _write_tag(out, field_number, _WIRE_VARINT)
    _write_varint(out, value)


def _write_bytes(out: bytearray, field_number: int, data: bytes) -> None:
    _write_tag(out, field_number, _WIRE_LENGTH_DELIMITED)
    _write_varint(out, len(data))
    out.extend(data)


def _write_string(out: bytearray, field_number: int, s: str) -> None:
    _write_bytes(out, field_number, s.encode("utf-8"))


def _write_string_if_nonempty(out: bytearray, field_number: int, s: str) -> None:
    if s:
        _write_string(out, field_number, s)


def _signed_to_uint64(value: int) -> int:
    """Reinterpret a signed 64-bit int as an unsigned 64-bit via two's complement.

    Matches Rust's ``value as u64`` behavior for int64 fields in proto3.
    """
    if value < 0:
        return value + (1 << 64)
    return value


def canonicalize_timestamp(seconds: int, nanos: int) -> bytes:
    """Canonicalize a google.protobuf.Timestamp given seconds + nanos.

    Mirrors ``canonicalize_timestamp`` in the Rust source.
    """
    out = bytearray()
    if seconds != 0:
        _write_varint_tag(out, 1, _signed_to_uint64(seconds))
    if nanos != 0:
        _write_varint_tag(out, 2, _signed_to_uint64(nanos))
    return bytes(out)


class EnvelopeFields:
    """Plain data holder for the fields of an Envelope used in canonicalization.

    The Python Envelope class (generated by protoc from envelope.proto) is what
    agents actually construct; this class exists so the canonicalizer stays
    independent of protoc output and can be tested without protobuf imports.
    """

    __slots__ = (
        "message_id",
        "correlation_id",
        "source_agent_id",
        "source_city",
        "target_topic",
        "timestamp_seconds",
        "timestamp_nanos",
        "timestamp_present",
        "priority",
        "type",
        "payload",
        "causal_message_ids",
        "schema_version",
        "nonce",
    )

    def __init__(
        self,
        *,
        message_id: str = "",
        correlation_id: str = "",
        source_agent_id: str = "",
        source_city: str = "",
        target_topic: str = "",
        timestamp_seconds: int = 0,
        timestamp_nanos: int = 0,
        timestamp_present: bool = False,
        priority: int = 0,
        type: int = 0,
        payload: bytes = b"",
        causal_message_ids: list[str] | None = None,
        schema_version: str = "",
        nonce: bytes = b"",
    ):
        self.message_id = message_id
        self.correlation_id = correlation_id
        self.source_agent_id = source_agent_id
        self.source_city = source_city
        self.target_topic = target_topic
        self.timestamp_seconds = timestamp_seconds
        self.timestamp_nanos = timestamp_nanos
        self.timestamp_present = timestamp_present
        self.priority = priority
        self.type = type
        self.payload = payload
        self.causal_message_ids = list(causal_message_ids or [])
        self.schema_version = schema_version
        self.nonce = nonce


def canonicalize_envelope(env: EnvelopeFields) -> bytes:
    """Produce the canonical bytes of an envelope for signing.

    Byte-for-byte compatible with ``core/obsidian-bus/src/canonical.rs``.
    """
    out = bytearray()

    # Tag 1: message_id (string) — strip if empty.
    _write_string_if_nonempty(out, 1, env.message_id)

    # Tag 2: correlation_id
    _write_string_if_nonempty(out, 2, env.correlation_id)

    # Tag 3: source_agent_id
    _write_string_if_nonempty(out, 3, env.source_agent_id)

    # Tag 4: source_city
    _write_string_if_nonempty(out, 4, env.source_city)

    # Tag 5: target_topic
    _write_string_if_nonempty(out, 5, env.target_topic)

    # Tag 6: timestamp (message) — always include if present
    if env.timestamp_present:
        inner = canonicalize_timestamp(env.timestamp_seconds, env.timestamp_nanos)
        _write_bytes(out, 6, inner)

    # Tag 7: priority (varint) — strip if 0
    if env.priority != 0:
        _write_varint_tag(out, 7, env.priority)

    # Tag 8: type (varint) — strip if 0 (UNSPECIFIED)
    if env.type != 0:
        _write_varint_tag(out, 8, env.type)

    # Tag 9: payload (bytes) — ALWAYS include
    _write_bytes(out, 9, env.payload)

    # Tag 10: causal_message_ids (repeated string) — in order
    for link in env.causal_message_ids:
        _write_string(out, 10, link)

    # Tag 11: schema_version
    _write_string_if_nonempty(out, 11, env.schema_version)

    # Tag 12: nonce (bytes) — ALWAYS include
    _write_bytes(out, 12, env.nonce)

    # Tag 13: signature — NEVER include in canonicalization
    return bytes(out)


def canonicalize_envelope_proto(envelope) -> bytes:
    """Convenience: accept a protoc-generated Envelope object and canonicalize.

    This is what callers use in practice. Delegates to ``canonicalize_envelope``
    after extracting the plain field values.

    The ``envelope`` argument must be an ``obsidian.Envelope`` produced from
    ``proto/envelope.proto`` via protoc.
    """
    fields = EnvelopeFields(
        message_id=envelope.message_id,
        correlation_id=envelope.correlation_id,
        source_agent_id=envelope.source_agent_id,
        source_city=envelope.source_city,
        target_topic=envelope.target_topic,
        timestamp_seconds=envelope.timestamp.seconds if envelope.HasField("timestamp") else 0,
        timestamp_nanos=envelope.timestamp.nanos if envelope.HasField("timestamp") else 0,
        timestamp_present=envelope.HasField("timestamp"),
        priority=envelope.priority,
        type=envelope.type,
        payload=envelope.payload,
        causal_message_ids=list(envelope.causal_message_ids),
        schema_version=envelope.schema_version,
        nonce=envelope.nonce,
    )
    return canonicalize_envelope(fields)
